/*
 * Austin Youngren
 * Guessing Game #1
 * Due: 09/30/2021
 * This code is intended for users to play a guessing game. 
 * The guess will compare to a randomly generated number.
 *  The user can repeat the game.
 */
//
//
//
import java.util.Random;
import java.util.Scanner;

public class GuessingGame {
	static Scanner input;
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner input;
		input = new Scanner(System.in);
		int guess;          // User inputs guess for game
		int answer;         // Random number that is generated by program
		Random randGen;		// Generates the random number
			
			//Getting the user's guess
		System.out.println("What number would you like to guess?");
		guess = input.nextInt();
		System.out.println("Your guess is " + guess);
		
		randGen = new Random();
		answer = randGen.nextInt(20 - 10 + 1) + 10;
			// Formula is (high - low + 1) + low
		System.out.println("The random number is " + answer);
		System.out.println("the guess is " + guess);
		
	}

}
// Had an issue connecting my github. 