/*
 * Austin Youngren
 * Guessing Game #1
 * Due: 09/30/2021
 * This code is intended for users to play a guessing game. 
 * The guess will compare to a randomly generated number.
 *  The user can repeat the game.
 */

import java.util.Random;
import java.util.Scanner;

public class GuessingGameAY2 {
	static Scanner input;
	public static void main(String[] args) {
		
		Scanner input;
		input = new Scanner(System.in);
		int guess;          // User inputs guess for game
		int answer;         // Random number that is generated by program
		Random randGen;		// Sets up and starts random number generator
		
		randGen = new Random();
		answer = randGen.nextInt(20 - 10 + 1) + 10;
			// Formula is (high - low + 1) + low
		
		System.out.println("The number is " + answer); // Outputs Random Number
			
			//Getting the user's guess
		System.out.println("What number would you like to guess?");
		guess = input.nextInt();
		System.out.println("Your guess is " + guess); //Outputs user's guess
		
		if (guess > answer) // Start of if statement. Sets up  true with: guess is greater than answer.
		{
			System.out.println("Your guess is to high"); // True statement output
		}
		else    // Sets up False statement
		{
			System.out.println("Your guess is to low"); // False statement output
		}
	}

}
// Problems: No Problems